// CE-04 Situation „Herr Demir" — Barrel Export
export { CE04_SIT_DEMIR_PATIENT } from "./patient";
export {
  CE04_SIT_DEMIR_WAHRNEHMEN,
  CE04_SIT_DEMIR_EINSCHAETZEN,
  CE04_SIT_DEMIR_INFORMIEREN,
  CE04_SIT_DEMIR_BERATEN,
  CE04_SIT_DEMIR_EVALUIEREN,
  CE04_SIT_DEMIR_DOKUMENTIEREN,
} from "./phases";
