// CE 05 — Manifest aller 20 Lektionen (40 UE)
// Quelle: specs/recherche-40ue-rheuma-curriculum.md

export interface LektionManifest {
  leId: string;
  ceId: string;
  block: "A" | "B" | "C" | "D" | "E" | "F";
  order: number;
  title: string;
  titleShort: string;
  ueCount: number;
  estimatedSteps: number;
  estimatedMinC1: number;
  estimatedMinB1: number;
  kompetenzbereiche: string[];
  bloomRange: [number, number];
  pruefungsrelevanz: "hoch" | "mittel";
  voraussetzungen: string[];
  status: "fertig" | "entwurf" | "geplant";
}

export const CE05_MANIFEST: LektionManifest[] = [
  // ==========================================
  // BLOCK A: Grundlagen (6 UE)
  // ==========================================
  {
    leId: "le-01-einfuehrung",
    ceId: "ce-05",
    block: "A",
    order: 1,
    title: "Einfuehrung — Der rheumatische Formenkreis",
    titleShort: "Einfuehrung Rheuma",
    ueCount: 2,
    estimatedSteps: 10,
    estimatedMinC1: 15,
    estimatedMinB1: 25,
    kompetenzbereiche: ["KB-I.1", "KB-V.1"],
    bloomRange: [1, 2],
    pruefungsrelevanz: "hoch",
    voraussetzungen: [],
    status: "fertig",
  },
  {
    leId: "le-02-anatomie",
    ceId: "ce-05",
    block: "A",
    order: 2,
    title: "Anatomie und Physiologie des Bewegungsapparats",
    titleShort: "Anatomie",
    ueCount: 3,
    estimatedSteps: 15,
    estimatedMinC1: 25,
    estimatedMinB1: 40,
    kompetenzbereiche: ["KB-I.1", "KB-V.1"],
    bloomRange: [1, 2],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-01-einfuehrung"],
    status: "fertig",
  },
  {
    leId: "le-03-pathophysiologie",
    ceId: "ce-05",
    block: "A",
    order: 3,
    title: "Pathophysiologie rheumatischer Erkrankungen",
    titleShort: "Pathophysiologie",
    ueCount: 3,
    estimatedSteps: 15,
    estimatedMinC1: 25,
    estimatedMinB1: 40,
    kompetenzbereiche: ["KB-I.1", "KB-V.1"],
    bloomRange: [2, 4],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-02-anatomie"],
    status: "fertig",
  },

  // ==========================================
  // BLOCK B: Krankheitsbilder (10 UE)
  // ==========================================
  {
    leId: "le-04-ra",
    ceId: "ce-05",
    block: "B",
    order: 4,
    title: "Rheumatoide Arthritis (RA)",
    titleShort: "RA",
    ueCount: 3,
    estimatedSteps: 17,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-I.3", "KB-II.1", "KB-II.2", "KB-III.2", "KB-V.1"],
    bloomRange: [1, 6],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-03-pathophysiologie"],
    status: "fertig",
  },
  {
    leId: "le-05-spa",
    ceId: "ce-05",
    block: "B",
    order: 5,
    title: "Spondyloarthritiden und weitere entzuendliche Arthritiden",
    titleShort: "SpA & Arthritiden",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 15,
    estimatedMinB1: 25,
    kompetenzbereiche: ["KB-I.1", "KB-V.1"],
    bloomRange: [1, 4],
    pruefungsrelevanz: "mittel",
    voraussetzungen: ["le-04-ra"],
    status: "fertig",
  },
  {
    leId: "le-06-gicht",
    ceId: "ce-05",
    block: "B",
    order: 6,
    title: "Kristallarthropathien — Gicht und Pseudogicht",
    titleShort: "Gicht",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 15,
    estimatedMinB1: 25,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-V.1"],
    bloomRange: [1, 5],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-03-pathophysiologie"],
    status: "fertig",
  },
  {
    leId: "le-07-kollagenosen",
    ceId: "ce-05",
    block: "B",
    order: 7,
    title: "Kollagenosen und Vaskulitiden",
    titleShort: "Kollagenosen",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 15,
    estimatedMinB1: 25,
    kompetenzbereiche: ["KB-I.1", "KB-V.1"],
    bloomRange: [1, 4],
    pruefungsrelevanz: "mittel",
    voraussetzungen: ["le-03-pathophysiologie"],
    status: "fertig",
  },

  // ==========================================
  // BLOCK C: Diagnostik und Therapie (7 UE)
  // ==========================================
  {
    leId: "le-08-diagnostik",
    ceId: "ce-05",
    block: "C",
    order: 8,
    title: "Diagnostik rheumatischer Erkrankungen",
    titleShort: "Diagnostik",
    ueCount: 3,
    estimatedSteps: 15,
    estimatedMinC1: 25,
    estimatedMinB1: 40,
    kompetenzbereiche: ["KB-I.1", "KB-III.2", "KB-V.1"],
    bloomRange: [1, 3],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-04-ra"],
    status: "fertig",
  },
  {
    leId: "le-09-dmards",
    ceId: "ce-05",
    block: "C",
    order: 9,
    title: "Medikamentoese Therapie — Basistherapie (DMARDs)",
    titleShort: "DMARDs",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-IV.1"],
    bloomRange: [1, 4],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-08-diagnostik"],
    status: "fertig",
  },
  {
    leId: "le-10-biologika",
    ceId: "ce-05",
    block: "C",
    order: 10,
    title: "Medikamentoese Therapie — Biologika, JAK-Inhibitoren, NSAR",
    titleShort: "Biologika & Co.",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-IV.1"],
    bloomRange: [1, 5],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-09-dmards"],
    status: "fertig",
  },

  // ==========================================
  // BLOCK D: Pflegerisches Handeln (11 UE)
  // ==========================================
  {
    leId: "le-11-assessments",
    ceId: "ce-05",
    block: "D",
    order: 11,
    title: "Pflegerische Assessments bei Rheuma",
    titleShort: "Assessments",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-V.1"],
    bloomRange: [2, 4],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-08-diagnostik"],
    status: "fertig",
  },
  {
    leId: "le-12-pflegeprozess-1",
    ceId: "ce-05",
    block: "D",
    order: 12,
    title: "Der pflegerische Prozess bei Rheuma — Teil 1",
    titleShort: "Pflegeprozess 1",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-II.2"],
    bloomRange: [3, 5],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-11-assessments"],
    status: "fertig",
  },
  {
    leId: "le-13-pflegeprozess-2",
    ceId: "ce-05",
    block: "D",
    order: 13,
    title: "Der pflegerische Prozess bei Rheuma — Teil 2",
    titleShort: "Pflegeprozess 2",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-IV.1"],
    bloomRange: [3, 5],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-12-pflegeprozess-1"],
    status: "fertig",
  },
  {
    leId: "le-14-schmerzmanagement",
    ceId: "ce-05",
    block: "D",
    order: 14,
    title: "Schmerzmanagement bei Rheuma",
    titleShort: "Schmerz",
    ueCount: 3,
    estimatedSteps: 15,
    estimatedMinC1: 25,
    estimatedMinB1: 40,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-IV.1", "KB-V.1"],
    bloomRange: [2, 5],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-11-assessments"],
    status: "fertig",
  },
  {
    leId: "le-15-interventionen",
    ceId: "ce-05",
    block: "D",
    order: 15,
    title: "Nicht-medikamentoese Interventionen",
    titleShort: "Interventionen",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 15,
    estimatedMinB1: 25,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-III.2"],
    bloomRange: [2, 3],
    pruefungsrelevanz: "mittel",
    voraussetzungen: ["le-12-pflegeprozess-1"],
    status: "fertig",
  },

  // ==========================================
  // BLOCK E: Beratung & Psychosoziales (6 UE)
  // ==========================================
  {
    leId: "le-16-edukation",
    ceId: "ce-05",
    block: "E",
    order: 16,
    title: "Patientenedukation und Beratung",
    titleShort: "Edukation",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-II.2", "KB-V.1"],
    bloomRange: [3, 6],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-12-pflegeprozess-1"],
    status: "geplant",
  },
  {
    leId: "le-17-psychosoziales",
    ceId: "ce-05",
    block: "E",
    order: 17,
    title: "Psychosoziale Aspekte und Krankheitsbewaeltigung",
    titleShort: "Psychosoziales",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 20,
    estimatedMinB1: 30,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-III.2", "KB-V.1"],
    bloomRange: [3, 5],
    pruefungsrelevanz: "mittel",
    voraussetzungen: ["le-04-ra"],
    status: "geplant",
  },
  {
    leId: "le-18-reha",
    ceId: "ce-05",
    block: "E",
    order: 18,
    title: "Rehabilitation, Hilfsmittel und interprofessionelle Zusammenarbeit",
    titleShort: "Reha & Team",
    ueCount: 2,
    estimatedSteps: 12,
    estimatedMinC1: 15,
    estimatedMinB1: 25,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-III.2", "KB-IV.1"],
    bloomRange: [1, 3],
    pruefungsrelevanz: "mittel",
    voraussetzungen: ["le-15-interventionen"],
    status: "geplant",
  },

  // ==========================================
  // BLOCK F: Vertiefung & Pruefung (2 UE)
  // ==========================================
  {
    leId: "le-19-evidenz",
    ceId: "ce-05",
    block: "F",
    order: 19,
    title: "Evidenzbasierte Pflege bei Rheuma und Leitlinien",
    titleShort: "Evidenz",
    ueCount: 1,
    estimatedSteps: 8,
    estimatedMinC1: 10,
    estimatedMinB1: 15,
    kompetenzbereiche: ["KB-IV.1", "KB-V.1"],
    bloomRange: [1, 5],
    pruefungsrelevanz: "mittel",
    voraussetzungen: ["le-14-schmerzmanagement"],
    status: "geplant",
  },
  {
    leId: "le-20-fallarbeit",
    ceId: "ce-05",
    block: "F",
    order: 20,
    title: "Komplexe Fallarbeit und Pruefungsvorbereitung",
    titleShort: "Fallarbeit",
    ueCount: 2,
    estimatedSteps: 15,
    estimatedMinC1: 25,
    estimatedMinB1: 40,
    kompetenzbereiche: ["KB-I.1", "KB-II.2", "KB-III.2", "KB-IV.1", "KB-V.1"],
    bloomRange: [3, 6],
    pruefungsrelevanz: "hoch",
    voraussetzungen: ["le-19-evidenz"],
    status: "geplant",
  },
];

// Hilfsfunktion: Lektion per leId finden
export function findLektion(leId: string): LektionManifest | undefined {
  return CE05_MANIFEST.find((l) => l.leId === leId);
}

// Blöcke mit Labels
export const BLOCK_LABELS: Record<string, string> = {
  A: "Grundlagen",
  B: "Krankheitsbilder",
  C: "Diagnostik & Therapie",
  D: "Pflegerisches Handeln",
  E: "Beratung & Psychosoziales",
  F: "Vertiefung & Pruefung",
};
