// Glossar — LE 08 Menschen in ihrer Ernährung unterstützen
// 42 Einträge aus Unterrichtsentwurf Abschnitt 7
// CONTENT-QUALITAET.md G1: Alle Fachbegriffe aus Steps
// CONTENT-QUALITAET.md G2: B1-Alltagswörter markiert

import type { GlossarEntry } from "../_types";

export const GLOSSAR_LE08: GlossarEntry[] = [
  // === Ernährungsstörungen & Zustände ===
  {
    begriff: "Malnutrition",
    erklaerung: "Mangelernährung — anhaltendes Defizit an Energie und/oder Nährstoffen, das zu messbaren Veränderungen der Körperzusammensetzung und Funktionseinbußen führt.",
    erklaerungB1: "Wenn man zu wenig oder das Falsche isst und der Körper nicht genug Nährstoffe bekommt.",
    uebersetzungTr: "Malnütrisyon",
    uebersetzungAr: "سوء التغذية",
    uebersetzungEn: "Malnutrition",
    vorsilbeNachsilbe: "mal- (schlecht) + nutritio (Ernährung)",
  },
  {
    begriff: "Adipositas",
    erklaerung: "Fettleibigkeit — krankhaftes Übergewicht mit einem BMI ≥ 30. Risikofaktor für Diabetes, Herz-Kreislauf-Erkrankungen und Gelenkprobleme.",
    erklaerungB1: "Starkes Übergewicht, das krank machen kann.",
    uebersetzungTr: "Obezite",
    uebersetzungAr: "السمنة",
    uebersetzungEn: "Obesity",
    vorsilbeNachsilbe: "adeps (Fett) + -ositas (Zustand)",
  },
  {
    begriff: "Kachexie",
    erklaerung: "Krankhafte Abmagerung — starker Gewichtsverlust mit Muskelschwund, häufig bei Tumorerkrankungen oder chronischen Entzündungen.",
    erklaerungB1: "Sehr starke Abmagerung bei schwerer Krankheit wie Krebs.",
    uebersetzungTr: "Kaşeksi",
    uebersetzungAr: "الدنف",
    uebersetzungEn: "Cachexia",
    vorsilbeNachsilbe: "kakos (schlecht) + hexis (Zustand)",
  },
  {
    begriff: "Sarkopenie",
    erklaerung: "Altersassoziierter Verlust von Skelettmuskulatur und -funktion, der zu Schwäche, Sturzgefahr und Immobilität führen kann.",
    erklaerungB1: "Wenn im Alter die Muskeln schwächer werden und man sich weniger bewegen kann.",
    uebersetzungTr: "Sarkopeni",
    uebersetzungAr: "ضمور العضلات",
    uebersetzungEn: "Sarcopenia",
    vorsilbeNachsilbe: "sarx (Fleisch/Muskel) + penia (Mangel)",
  },
  {
    begriff: "Dehydratation",
    erklaerung: "Flüssigkeitsmangel — Verminderung des Gesamtkörperwassers unter den physiologischen Bedarf.",
    erklaerungB1: "Wenn der Körper zu wenig Wasser hat.",
    uebersetzungTr: "Dehidrasyon",
    uebersetzungAr: "الجفاف",
    uebersetzungEn: "Dehydration",
    istB1Alltagswort: true,
    vorsilbeNachsilbe: "de- (weg) + hydro (Wasser) + -ation (Vorgang)",
  },
  {
    begriff: "Exsikkose",
    erklaerung: "Austrocknung — klinische Zeichen des Flüssigkeitsmangels wie stehende Hautfalten, trockene Schleimhäute, konzentrierter Urin und Verwirrtheit.",
    erklaerungB1: "Starker Wassermangel — man sieht es an der trockenen Haut und den trockenen Lippen.",
    uebersetzungTr: "Eksikoz",
    uebersetzungAr: "التجفاف",
    uebersetzungEn: "Desiccosis / Exsiccosis",
    vorsilbeNachsilbe: "ex- (heraus) + siccare (trocknen)",
  },
  {
    begriff: "Refeeding-Syndrom",
    erklaerung: "Lebensbedrohliche Komplikation bei zu schneller Wiederernährung nach Hungerzustand. Leitsymptom: Hypophosphatämie mit Herzrhythmusstörungen.",
    erklaerungB1: "Wenn man einem sehr ausgezehrten Menschen zu schnell zu viel Essen gibt — das kann gefährlich werden.",
    uebersetzungTr: "Yeniden beslenme sendromu",
    uebersetzungAr: "متلازمة إعادة التغذية",
    uebersetzungEn: "Refeeding syndrome",
  },
  {
    begriff: "Altersanorexie",
    erklaerung: "Physiologische Appetitlosigkeit im Alter mit vermindertem Durstgefühl, die zu Mangelernährung und Dehydratation führen kann.",
    erklaerungB1: "Im Alter hat man oft weniger Hunger und Durst — der Körper merkt nicht mehr, dass er etwas braucht.",
    uebersetzungTr: "Yaşlılık iştahsızlığı",
    uebersetzungAr: "فقدان الشهية المرتبط بالعمر",
    uebersetzungEn: "Age-related anorexia",
  },

  // === Schlucken & Aspiration ===
  {
    begriff: "Dysphagie",
    erklaerung: "Schluckstörung — Beeinträchtigung des Schluckvorgangs in einer oder mehreren Phasen (oral, pharyngeal, ösophageal).",
    erklaerungB1: "Wenn man nicht richtig schlucken kann und sich leicht verschluckt.",
    uebersetzungTr: "Disfaji",
    uebersetzungAr: "عسر البلع",
    uebersetzungEn: "Dysphagia",
    vorsilbeNachsilbe: "dys- (gestört) + phagein (schlucken)",
  },
  {
    begriff: "Aspiration",
    erklaerung: "Eindringen von Material (Nahrung, Flüssigkeit, Magensaft) in die unteren Atemwege unterhalb der Stimmritze.",
    erklaerungB1: "Wenn Essen oder Trinken versehentlich in die Lunge kommt.",
    uebersetzungTr: "Aspirasyon",
    uebersetzungAr: "الشفط",
    uebersetzungEn: "Aspiration",
    istB1Alltagswort: true,
    vorsilbeNachsilbe: "a- (zu) + spirare (atmen)",
  },
  {
    begriff: "Aspirationspneumonie",
    erklaerung: "Lungenentzündung durch eingeatmetes Material (Nahrung, Flüssigkeit, Magensaft) in die unteren Atemwege.",
    erklaerungB1: "Eine Lungenentzündung, weil Essen in die Lunge gekommen ist.",
    uebersetzungTr: "Aspirasyon pnömonisi",
    uebersetzungAr: "الالتهاب الرئوي الاستنشاقي",
    uebersetzungEn: "Aspiration pneumonia",
    vorsilbeNachsilbe: "Aspiration + pneumo- (Lunge) + -ie (Erkrankung)",
  },
  {
    begriff: "F.O.T.T.",
    erklaerung: "Facio-Orale Trakt-Therapie — therapeutisches Konzept zur Behandlung von Schluck-, Ess- und Trinkstörungen bei neurologischen Patienten.",
    erklaerungB1: "Eine spezielle Therapie bei Schluckstörungen, die Mund und Gesicht trainiert.",
    uebersetzungTr: "F.O.T.T. (Facio-Oral Trakt Terapisi)",
    uebersetzungAr: "علاج المسالك الوجهية الفموية",
    uebersetzungEn: "Facio-Oral Tract Therapy (F.O.T.T.)",
  },
  {
    begriff: "Andickungsmittel",
    erklaerung: "Substanz zum Eindicken von Flüssigkeiten bei Schluckstörungen (z. B. Nutilis), um die Aspirationsgefahr zu verringern.",
    erklaerungB1: "Ein Pulver, das man in Getränke mischt, damit sie dicker werden und man sich nicht verschluckt.",
    uebersetzungTr: "Kıvam artırıcı",
    uebersetzungAr: "مادة مُكثفة",
    uebersetzungEn: "Thickening agent",
    istB1Alltagswort: true,
  },

  // === Assessments & Screening ===
  {
    begriff: "BMI",
    erklaerung: "Body-Mass-Index — Maßzahl für das Verhältnis von Körpergewicht zu Körpergröße (kg/m²). Orientierungswert, aber allein nicht aussagekräftig.",
    erklaerungB1: "Eine Zahl, die zeigt, ob man normal-, unter- oder übergewichtig ist.",
    uebersetzungTr: "Vücut Kitle İndeksi (VKİ)",
    uebersetzungAr: "مؤشر كتلة الجسم",
    uebersetzungEn: "Body Mass Index (BMI)",
    istB1Alltagswort: true,
  },
  {
    begriff: "MNA",
    erklaerung: "Mini Nutritional Assessment — standardisiertes 2-stufiges Screening-Instrument für Mangelernährung im geriatrischen Setting. Ergebnisse: 24–30 = normal, 17–23,5 = Risiko, <17 = Mangelernährung.",
    erklaerungB1: "Ein Fragebogen, der zeigt, ob ein älterer Mensch zu wenig isst.",
    uebersetzungTr: "Mini Nütrisyonel Değerlendirme",
    uebersetzungAr: "التقييم التغذوي المصغر",
    uebersetzungEn: "Mini Nutritional Assessment (MNA)",
  },
  {
    begriff: "NRS 2002",
    erklaerung: "Nutritional Risk Screening 2002 — standardisiertes Screening für Mangelernährungsrisiko im Krankenhaus. Score ≥ 3 = ernährungsmedizinische Intervention nötig.",
    erklaerungB1: "Ein Test im Krankenhaus, der zeigt, ob ein Patient zu wenig Nährstoffe bekommt.",
    uebersetzungTr: "Nütrisyonel Risk Taraması 2002",
    uebersetzungAr: "فحص مخاطر سوء التغذية 2002",
    uebersetzungEn: "Nutritional Risk Screening 2002 (NRS 2002)",
  },
  {
    begriff: "Perzentilenkurve",
    erklaerung: "Wachstumskurve, die zeigt, ob ein Kind sich in Gewicht und Länge altersgemäß entwickelt. Werte unter der 3. Perzentile oder über der 97. Perzentile sind auffällig.",
    erklaerungB1: "Eine Kurve im gelben Heft, die zeigt, ob das Kind normal wächst und zunimmt.",
    uebersetzungTr: "Persantil eğrisi",
    uebersetzungAr: "منحنى المئوية",
    uebersetzungEn: "Percentile curve",
    vorsilbeNachsilbe: "Perzentile (Hundertstel) + Kurve (Linie)",
  },

  // === Nährstoffe & Energiebedarf ===
  {
    begriff: "Makronährstoffe",
    erklaerung: "Nährstoffe, die der Körper in großen Mengen braucht und die Energie liefern: Kohlenhydrate (4 kcal/g), Proteine (4 kcal/g), Fette (9 kcal/g).",
    erklaerungB1: "Die großen Nährstoffe im Essen: Zucker, Eiweiß und Fett — die geben Energie.",
    uebersetzungTr: "Makro besin öğeleri",
    uebersetzungAr: "المغذيات الكبرى",
    uebersetzungEn: "Macronutrients",
    vorsilbeNachsilbe: "makro- (groß) + Nährstoffe",
  },
  {
    begriff: "Mikronährstoffe",
    erklaerung: "Nährstoffe, die der Körper in kleinen Mengen braucht: Vitamine und Mineralstoffe. Liefern keine Energie, sind aber essentiell für Stoffwechselprozesse.",
    erklaerungB1: "Vitamine und Mineralstoffe — man braucht nur wenig davon, aber sie sind sehr wichtig.",
    uebersetzungTr: "Mikro besin öğeleri",
    uebersetzungAr: "المغذيات الدقيقة",
    uebersetzungEn: "Micronutrients",
    vorsilbeNachsilbe: "mikro- (klein) + Nährstoffe",
  },
  {
    begriff: "Grundumsatz",
    erklaerung: "Energiebedarf des Körpers in völliger Ruhe — für Atmung, Herzschlag, Organfunktion und Temperaturregulation.",
    erklaerungB1: "Die Energie, die der Körper braucht, wenn man nur liegt und nichts tut.",
    uebersetzungTr: "Bazal metabolizma hızı",
    uebersetzungAr: "معدل الأيض الأساسي",
    uebersetzungEn: "Basal metabolic rate (BMR)",
    istB1Alltagswort: true,
  },
  {
    begriff: "PAL-Wert",
    erklaerung: "Physical Activity Level — Faktor, der den Aktivitätsgrad beschreibt. Gesamtenergiebedarf = Grundumsatz × PAL-Wert.",
    erklaerungB1: "Eine Zahl, die zeigt, wie aktiv jemand ist — liegt jemand nur im Bett oder bewegt er sich viel.",
    uebersetzungTr: "Fiziksel Aktivite Düzeyi",
    uebersetzungAr: "مستوى النشاط البدني",
    uebersetzungEn: "Physical Activity Level (PAL)",
  },

  // === Verdauung ===
  {
    begriff: "Peristaltik",
    erklaerung: "Wellenförmige Muskelbewegung der Darmwand, die den Nahrungsbrei in Richtung Rektum transportiert. Funktioniert auch gegen die Schwerkraft.",
    erklaerungB1: "Die Darmmuskeln bewegen sich wellenförmig und schieben das Essen weiter.",
    uebersetzungTr: "Peristaltizm",
    uebersetzungAr: "الحركة التمعجية",
    uebersetzungEn: "Peristalsis",
    vorsilbeNachsilbe: "peri- (herum) + stalsis (Zusammenziehen)",
  },
  {
    begriff: "Reflux",
    erklaerung: "Rückfluss von saurem Mageninhalt in die Speiseröhre durch Insuffizienz des unteren Ösophagussphinkters.",
    erklaerungB1: "Wenn der saure Mageninhalt zurück in die Speiseröhre fließt — das brennt.",
    uebersetzungTr: "Reflü",
    uebersetzungAr: "الارتجاع",
    uebersetzungEn: "Reflux",
    vorsilbeNachsilbe: "re- (zurück) + flux (Fluss)",
  },
  {
    begriff: "Obstipation",
    erklaerung: "Verstopfung — zu seltene (< 3×/Woche) und/oder erschwerte Stuhlentleerung mit hartem Stuhl.",
    erklaerungB1: "Wenn man Probleme hat, auf Toilette zu gehen und der Stuhl zu hart ist.",
    uebersetzungTr: "Kabızlık",
    uebersetzungAr: "الإمساك",
    uebersetzungEn: "Constipation",
    istB1Alltagswort: true,
    vorsilbeNachsilbe: "ob- (gegen) + stipare (stopfen)",
  },

  // === Künstliche Ernährung ===
  {
    begriff: "Enterale Ernährung",
    erklaerung: "Ernährung über den Magen-Darm-Trakt — entweder oral (durch den Mund) oder per Sonde (nasogastral, PEG).",
    erklaerungB1: "Ernährung, die über den Magen geht — entweder normal essen oder über einen Schlauch.",
    uebersetzungTr: "Enteral beslenme",
    uebersetzungAr: "التغذية المعوية",
    uebersetzungEn: "Enteral nutrition",
    vorsilbeNachsilbe: "enteron (Darm) + -al (betreffend)",
  },
  {
    begriff: "Parenterale Ernährung",
    erklaerung: "Ernährung unter Umgehung des Magen-Darm-Trakts — Nährstofflösungen werden direkt intravenös verabreicht.",
    erklaerungB1: "Nährstoffe direkt über eine Infusion ins Blut geben, ohne den Magen.",
    uebersetzungTr: "Parenteral beslenme",
    uebersetzungAr: "التغذية الوريدية",
    uebersetzungEn: "Parenteral nutrition",
    vorsilbeNachsilbe: "para- (neben) + enteron (Darm) = am Darm vorbei",
  },
  {
    begriff: "PEG",
    erklaerung: "Perkutane Endoskopische Gastrostomie — Ernährungssonde, die endoskopisch durch die Bauchdecke direkt in den Magen eingeführt wird.",
    erklaerungB1: "Ein kleiner Schlauch durch die Bauchdecke direkt in den Magen, um Nahrung zu geben.",
    uebersetzungTr: "PEG (Perkutan Endoskopik Gastrostomi)",
    uebersetzungAr: "فغر المعدة بالتنظير عبر الجلد",
    uebersetzungEn: "Percutaneous Endoscopic Gastrostomy (PEG)",
    vorsilbeNachsilbe: "per- (durch) + kutan (Haut) + gastro- (Magen) + -stomie (Öffnung)",
  },
  {
    begriff: "Nasogastrale Sonde",
    erklaerung: "Ernährungssonde, die über die Nase durch den Ösophagus in den Magen geführt wird. Für kurzfristige Sondenernährung (bis ca. 4 Wochen).",
    erklaerungB1: "Ein dünner Schlauch, der durch die Nase bis in den Magen geht.",
    uebersetzungTr: "Nazogastrik sonda",
    uebersetzungAr: "أنبوب أنفي معدي",
    uebersetzungEn: "Nasogastric tube (NGT)",
    vorsilbeNachsilbe: "naso- (Nase) + gastr- (Magen) + -al (betreffend)",
  },
  {
    begriff: "Sondennahrung",
    erklaerung: "Spezielle industriell hergestellte Flüssignahrung für die Verabreichung über Ernährungssonden, mit definiertem Nährstoff- und Energiegehalt.",
    erklaerungB1: "Flüssiges Essen, das über einen Schlauch in den Magen kommt.",
    uebersetzungTr: "Sonda beslenmesi",
    uebersetzungAr: "تغذية أنبوبية",
    uebersetzungEn: "Tube feed / Tube feeding formula",
    istB1Alltagswort: true,
  },
  {
    begriff: "Bolus-Gabe",
    erklaerung: "Portionsweise Gabe der Sondennahrung (z. B. 200 ml alle 3 Stunden) im Gegensatz zur kontinuierlichen Verabreichung per Pumpe.",
    erklaerungB1: "Die Sondennahrung wird in einzelnen Portionen gegeben, nicht ständig.",
    uebersetzungTr: "Bolus uygulama",
    uebersetzungAr: "إعطاء جرعة واحدة",
    uebersetzungEn: "Bolus feeding",
    vorsilbeNachsilbe: "bolus (Bissen/Klumpen) + Gabe",
  },

  // === Dokumentation & Bilanzierung ===
  {
    begriff: "Flüssigkeitsbilanz",
    erklaerung: "Dokumentation von Einfuhr (oral, Infusion, Sonde) und Ausfuhr (Urin, Drainage, Erbrechen, Schweiß) von Flüssigkeit über 24 Stunden.",
    erklaerungB1: "Man schreibt auf, wie viel ein Patient trinkt und wie viel er ausscheidet — das muss ungefähr gleich sein.",
    uebersetzungTr: "Sıvı dengesi",
    uebersetzungAr: "ميزان السوائل",
    uebersetzungEn: "Fluid balance",
    istB1Alltagswort: true,
  },
  {
    begriff: "Bilanzierung",
    erklaerung: "Aufrechnung von Flüssigkeitseinfuhr und -ausfuhr zur Beurteilung des Flüssigkeitshaushalts.",
    erklaerungB1: "Aufschreiben, was ein Patient trinkt und was er ausscheidet.",
    uebersetzungTr: "Bilanço yapma",
    uebersetzungAr: "حساب الميزانية",
    uebersetzungEn: "Fluid balance monitoring",
  },
  {
    begriff: "Essprotokoll",
    erklaerung: "Dokumentation der aufgenommenen Nahrung und Trinkmenge über einen definierten Zeitraum zur Beurteilung der Ernährungssituation.",
    erklaerungB1: "Ein Blatt, wo man aufschreibt, was und wie viel jemand gegessen und getrunken hat.",
    uebersetzungTr: "Beslenme protokolü",
    uebersetzungAr: "بروتوكول الأكل",
    uebersetzungEn: "Food intake record / Dietary log",
    istB1Alltagswort: true,
  },
  {
    begriff: "Kostform",
    erklaerung: "Art der Nahrungszubereitung, angepasst an den Gesundheitszustand des Patienten (z. B. passiert, püriert, leichte Vollkost, Diabeteskost).",
    erklaerungB1: "Die Art, wie das Essen zubereitet wird — zum Beispiel püriert, flüssig oder normal.",
    uebersetzungTr: "Diyet şekli",
    uebersetzungAr: "نوع النظام الغذائي",
    uebersetzungEn: "Diet form / Dietary modification",
    istB1Alltagswort: true,
  },

  // === Mundgesundheit ===
  {
    begriff: "Xerostomie",
    erklaerung: "Mundtrockenheit — reduzierte Speichelproduktion, häufig als Nebenwirkung von Medikamenten oder bei Dehydratation.",
    erklaerungB1: "Trockener Mund — wenn der Körper zu wenig Speichel macht.",
    uebersetzungTr: "Ağız kuruluğu",
    uebersetzungAr: "جفاف الفم",
    uebersetzungEn: "Xerostomia",
    vorsilbeNachsilbe: "xero- (trocken) + stoma (Mund)",
  },
  {
    begriff: "Stomatitis",
    erklaerung: "Entzündung der Mundschleimhaut mit Rötung, Schwellung und Schmerzen, die die Nahrungsaufnahme erschwert.",
    erklaerungB1: "Wenn die Schleimhaut im Mund entzündet und wund ist.",
    uebersetzungTr: "Stomatit",
    uebersetzungAr: "التهاب الفم",
    uebersetzungEn: "Stomatitis",
    vorsilbeNachsilbe: "stoma (Mund) + -itis (Entzündung)",
  },
  {
    begriff: "Soor",
    erklaerung: "Pilzinfektion der Mundschleimhaut durch Candida albicans, erkennbar an weißen, abwischbaren Belägen.",
    erklaerungB1: "Weißer Pilzbelag im Mund, der weh tun kann.",
    uebersetzungTr: "Oral kandidiyazis",
    uebersetzungAr: "داء المبيضات الفموي",
    uebersetzungEn: "Oral thrush / Oral candidiasis",
  },

  // === Pädiatrie ===
  {
    begriff: "Beikost",
    erklaerung: "Alle Nahrungsmittel außer Muttermilch und Milchfertignahrung für Säuglinge, die ab dem 5.–7. Monat eingeführt werden.",
    erklaerungB1: "Die erste Breinahrung, die ein Baby zusätzlich zur Milch bekommt.",
    uebersetzungTr: "Ek gıda",
    uebersetzungAr: "الأطعمة التكميلية",
    uebersetzungEn: "Complementary food / Weaning food",
    istB1Alltagswort: true,
    vorsilbeNachsilbe: "Bei- (dazu) + Kost (Nahrung)",
  },
  {
    begriff: "Gedeihstörung",
    erklaerung: "Unzureichende Gewichtszunahme oder Gewichtsverlust bei Säuglingen und Kleinkindern, erkennbar an Abweichung von den Perzentilenkurven.",
    erklaerungB1: "Wenn ein Baby nicht richtig zunimmt oder sogar abnimmt.",
    uebersetzungTr: "Gelişme geriliği",
    uebersetzungAr: "فشل النمو",
    uebersetzungEn: "Failure to thrive (FTT)",
    vorsilbeNachsilbe: "Gedeih- (wachsen) + Störung (Problem)",
  },

  // === Hilfsmittel & Spezialnahrung ===
  {
    begriff: "Trinknahrung",
    erklaerung: "Hochkalorische Flüssignahrung als orale Ergänzung bei Mangelernährung (z. B. Fresubin, Fortimel), ca. 200–400 kcal pro 200 ml.",
    erklaerungB1: "Nährstoffreiche Getränke, die man extra trinkt, wenn man zu wenig isst.",
    uebersetzungTr: "Takviye içeceği",
    uebersetzungAr: "مكمل غذائي سائل",
    uebersetzungEn: "Oral nutritional supplement (ONS)",
    istB1Alltagswort: true,
  },
  {
    begriff: "Fingerfood",
    erklaerung: "Kleine, mit den Fingern greifbare Nahrungsstücke, besonders geeignet für Menschen mit Demenz, die mit Besteck nicht mehr umgehen können.",
    erklaerungB1: "Kleine Häppchen, die man mit den Fingern essen kann — gut für Menschen mit Demenz.",
    uebersetzungTr: "Parmak yiyecekleri",
    uebersetzungAr: "طعام يؤكل باليد",
    uebersetzungEn: "Finger food",
    istB1Alltagswort: true,
  },

  // === Laborwerte & Komplikationen ===
  {
    begriff: "Hypophosphatämie",
    erklaerung: "Zu niedriger Phosphatspiegel im Blut — Leitsymptom des Refeeding-Syndroms, kann zu Herzrhythmusstörungen und Atemversagen führen.",
    erklaerungB1: "Zu wenig Phosphat im Blut — das passiert, wenn man einem ausgezehrten Menschen zu schnell Essen gibt.",
    uebersetzungTr: "Hipofosfatemi",
    uebersetzungAr: "نقص فوسفات الدم",
    uebersetzungEn: "Hypophosphataemia",
    vorsilbeNachsilbe: "hypo- (zu wenig) + phosphat + -ämie (im Blut)",
  },
];
