// Karteikarten — LE 08 Menschen in ihrer Ernährung unterstützen
// 38 Karten, 5 Kategorien (fachbegriff, fakt, handlung, assessment, recht)
// 3 Leitfälle: Elisabeth Kramer (42, MS+Dysphagie), Baby Emre (6 Mo, Gedeihstörung), Walter Bergmann (84, Demenz+PEG)
// 60%+ prüfungsrelevant (24/38 = 63%)

import type { KarteikarteVorlage } from "../_types";

export const KARTEIKARTEN_LE08: KarteikarteVorlage[] = [

  // ===================================================================
  // FACHBEGRIFF (8 Karten)
  // ===================================================================

  {
    id: "le08-kk-01",
    vorderseite: "Was bedeutet Dysphagie?",
    rueckseiteC1: "Schluckstörung — Beeinträchtigung des Schluckvorgangs in oraler, pharyngealer oder ösophagealer Phase.",
    rueckseiteB1: "Man kann nicht richtig schlucken. Es gibt drei Phasen beim Schlucken, die gestört sein können.",
    tag: "krankheitslehre",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 358",
  },
  {
    id: "le08-kk-02",
    vorderseite: "Welche drei Schluckphasen gibt es?",
    rueckseiteC1: "Orale Phase (Kauen, Bolusbildung), pharyngeale Phase (Schluckreflex, Kehldeckelverschluss) und ösophageale Phase (peristaltischer Transport).",
    rueckseiteB1: "1) Mund: kauen und formen. 2) Rachen: Schluckreflex. 3) Speiseröhre: Essen rutscht zum Magen.",
    tag: "anatomie",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "I Care Anatomie Physiologie Thieme 2020, S. 412",
  },
  {
    id: "le08-kk-03",
    vorderseite: "Was ist eine Aspiration?",
    rueckseiteC1: "Eindringen von Nahrung, Flüssigkeit oder Magensaft in die unteren Atemwege unterhalb der Stimmritze.",
    rueckseiteB1: "Wenn Essen oder Trinken in die Lunge kommt. Das ist gefährlich.",
    tag: "krankheitslehre",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 359",
  },
  {
    id: "le08-kk-04",
    vorderseite: "Was bedeutet Malnutrition?",
    rueckseiteC1: "Mangelernährung — anhaltendes Defizit an Energie und/oder Nährstoffen mit messbaren Veränderungen der Körperzusammensetzung.",
    rueckseiteB1: "Man bekommt über längere Zeit zu wenig oder das Falsche zu essen. Der Körper wird schwächer.",
    tag: "krankheitslehre",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "DNQP Expertenstandard Ernährungsmanagement 2017, S. 24",
  },
  {
    id: "le08-kk-05",
    vorderseite: "Was ist eine PEG-Sonde?",
    rueckseiteC1: "Perkutane Endoskopische Gastrostomie — Ernährungssonde, die endoskopisch durch die Bauchdecke direkt in den Magen eingeführt wird.",
    rueckseiteB1: "Ein kleiner Schlauch durch die Bauchdecke in den Magen. So kann man Nahrung direkt geben.",
    tag: "pflege",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 365",
  },
  {
    id: "le08-kk-06",
    vorderseite: "Was ist das Refeeding-Syndrom?",
    rueckseiteC1: "Lebensbedrohliche Komplikation bei zu schneller Wiederernährung nach Hungerzustand. Leitsymptom: Hypophosphatämie mit Herzrhythmusstörungen.",
    rueckseiteB1: "Wenn ein sehr abgemagerter Mensch zu schnell Essen bekommt, kann das lebensgefährlich sein.",
    tag: "krankheitslehre",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 370",
  },
  {
    id: "le08-kk-07",
    vorderseite: "Was ist Kachexie?",
    rueckseiteC1: "Krankhafte Abmagerung mit Muskelschwund, häufig bei Tumorerkrankungen oder chronischen Entzündungen.",
    rueckseiteB1: "Sehr starke Abmagerung bei schwerer Krankheit. Man verliert viel Muskeln und Gewicht.",
    tag: "krankheitslehre",
    kategorie: "fachbegriff",
    pruefungsrelevant: false,
    quelle: "I Care Krankheitslehre Thieme 2020, S. 290",
  },
  {
    id: "le08-kk-08",
    vorderseite: "Was ist stille Aspiration?",
    rueckseiteC1: "Aspiration ohne Hustenreflex — Nahrung gelangt unbemerkt in die Atemwege. Häufig bei Demenz oder schwerer neurologischer Erkrankung.",
    rueckseiteB1: "Essen kommt in die Lunge, aber der Patient hustet nicht. Das ist gefährlich, weil man es nicht merkt.",
    tag: "krankheitslehre",
    kategorie: "fachbegriff",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 359; Leitlinie Neurogene Dysphagie DGN 2020",
  },

  // ===================================================================
  // FAKT (8 Karten)
  // ===================================================================

  {
    id: "le08-kk-09",
    vorderseite: "Wie lautet die BMI-Formel und welche Grenzwerte gelten?",
    rueckseiteC1: "BMI = kg/m². Untergewicht < 18,5, Normalgewicht 18,5–24,9, Übergewicht 25–29,9, Adipositas ≥ 30.",
    rueckseiteB1: "Gewicht geteilt durch Größe mal Größe. Normal ist 18,5 bis 24,9. Ab 30 ist man stark übergewichtig.",
    tag: "pflege",
    kategorie: "fakt",
    pruefungsrelevant: true,
    quelle: "WHO Klassifikation 2000; I Care Pflege Thieme 2020, S. 341",
  },
  {
    id: "le08-kk-10",
    vorderseite: "Wie viel Flüssigkeit braucht ein Erwachsener pro Tag?",
    rueckseiteC1: "Faustregel: 30 ml/kg Körpergewicht/Tag. Bei 70 kg also ca. 2100 ml. Erhöht bei Fieber (+500 ml pro 1 °C über 37 °C).",
    rueckseiteB1: "Etwa 30 ml für jedes Kilo Körpergewicht. Bei 70 kg sind das ungefähr 2 Liter am Tag.",
    tag: "pflege",
    kategorie: "fakt",
    pruefungsrelevant: true,
    quelle: "DGE Referenzwerte 2023; I Care Pflege Thieme 2020, S. 347",
  },
  {
    id: "le08-kk-11",
    vorderseite: "Welchen Energiegehalt haben die drei Makronährstoffe?",
    rueckseiteC1: "Kohlenhydrate: 4 kcal/g, Proteine: 4 kcal/g, Fette: 9 kcal/g. Alkohol liefert 7 kcal/g.",
    rueckseiteB1: "Zucker und Eiweiß geben je 4 kcal pro Gramm. Fett gibt 9 kcal — mehr als doppelt so viel.",
    tag: "anatomie",
    kategorie: "fakt",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 339",
  },
  {
    id: "le08-kk-12",
    vorderseite: "Ab welcher Perzentile ist ein Säugling auffällig untergewichtig?",
    rueckseiteC1: "Unter der 3. Perzentile. Auch ein Kreuzen von zwei Perzentilen nach unten ist ein Warnsignal für Gedeihstörung.",
    rueckseiteB1: "Wenn das Gewicht unter der 3. Linie auf der Wachstumskurve liegt, ist das zu wenig.",
    tag: "pflege",
    kategorie: "fakt",
    pruefungsrelevant: true,
    quelle: "Leitlinie Gedeihstörung DGKJ 2020",
  },
  {
    id: "le08-kk-13",
    vorderseite: "Wie lange darf eine nasogastrale Sonde maximal liegen?",
    rueckseiteC1: "Etwa 4–6 Wochen. Bei längerem Bedarf ist eine PEG-Anlage indiziert.",
    rueckseiteB1: "Nicht länger als 4 bis 6 Wochen. Wenn es länger dauert, braucht man eine PEG-Sonde.",
    tag: "pflege",
    kategorie: "fakt",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 363",
  },
  {
    id: "le08-kk-14",
    vorderseite: "Wann wird Beikost beim Säugling eingeführt?",
    rueckseiteC1: "Ab dem 5.–7. Lebensmonat. Nicht vor dem vollendeten 4. Monat. Honig erst ab dem 1. Geburtstag (Botulismus-Risiko).",
    rueckseiteB1: "Zwischen dem 5. und 7. Monat bekommt das Baby den ersten Brei. Honig ist bis zum 1. Geburtstag verboten.",
    tag: "pflege",
    kategorie: "fakt",
    pruefungsrelevant: false,
    quelle: "DGE Handlungsempfehlungen Säuglingsernährung 2022",
  },
  {
    id: "le08-kk-15",
    vorderseite: "Warum ist der Schnabelbecher bei Dysphagie verboten?",
    rueckseiteC1: "Er erzwingt eine Kopfüberstreckung. Der Kehldeckel schließt nicht vollständig und Flüssigkeit kann aspiriert werden.",
    rueckseiteB1: "Der Kopf geht beim Trinken nach hinten. Dann schließt der Kehldeckel nicht und Flüssigkeit kann in die Lunge kommen.",
    tag: "pflege",
    kategorie: "fakt",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 475",
  },
  {
    id: "le08-kk-16",
    vorderseite: "Wie viel Prozent der Krankenhauspatienten sind mangelernährt?",
    rueckseiteC1: "32–55 % aller Krankenhauspatienten, 18 % bereits bei Aufnahme. Mangelernährung erhöht Komplikationsrate und Liegedauer.",
    rueckseiteB1: "Fast jeder dritte bis zweite Patient im Krankenhaus ist mangelernährt. Viele schon beim Aufnehmen.",
    tag: "krankheitslehre",
    kategorie: "fakt",
    pruefungsrelevant: false,
    quelle: "DNQP Expertenstandard Ernährungsmanagement 2017; I Care Pflege Thieme 2020, S. 408",
  },

  // ===================================================================
  // HANDLUNG (8 Karten)
  // ===================================================================

  {
    id: "le08-kk-17",
    vorderseite: "Wie positionierst du Elisabeth Kramer beim Essen?",
    rueckseiteC1: "Aufrechte Sitzposition (90°), Chin-Tuck (Kinn leicht zur Brust), keine Reklination. Nach dem Essen 20 Minuten aufrecht bleiben.",
    rueckseiteB1: "Aufrecht sitzen, Kinn leicht zur Brust. Nicht zurücklehnen. Nach dem Essen noch 20 Minuten sitzen bleiben.",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 360; F.O.T.T. Leitlinie",
  },
  {
    id: "le08-kk-18",
    vorderseite: "Worauf achtest du bei der Mundpflege vor dem Essen?",
    rueckseiteC1: "Mundschleimhaut auf Soor, Stomatitis und Xerostomie inspizieren. Mund befeuchten, Prothesensitz prüfen, Speichelfluss anregen.",
    rueckseiteB1: "Mund anschauen: Ist er trocken oder wund? Sitzt die Zahnprothese gut? Mund befeuchten.",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "DNQP Expertenstandard Ernährungsmanagement 2017, S. 46",
  },
  {
    id: "le08-kk-19",
    vorderseite: "Wie verabreichst du Sondennahrung über eine PEG?",
    rueckseiteC1: "Oberkörper 30–45° hochlagern, Sondenlage prüfen, Nahrung auf Raumtemperatur, Sonde vor und nach Gabe mit 30–50 ml Wasser spülen.",
    rueckseiteB1: "Oberkörper hoch, Sonde prüfen, Nahrung nicht kalt geben. Sonde vorher und nachher mit Wasser spülen.",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 366–367",
  },
  {
    id: "le08-kk-20",
    vorderseite: "Was dokumentierst du bei einer Flüssigkeitsbilanz?",
    rueckseiteC1: "Einfuhr (oral, Infusion, Sonde) und Ausfuhr (Urin, Drainage, Erbrechen, Schweiß) über 24 h. Bilanz = Einfuhr minus Ausfuhr.",
    rueckseiteB1: "Alles aufschreiben, was reinkommt und was rausgeht. Am Ende vergleichen: Ist es ungefähr gleich?",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 349",
  },
  {
    id: "le08-kk-21",
    vorderseite: "Wie erkennst du Aspirationszeichen bei Elisabeth Kramer?",
    rueckseiteC1: "Husten beim Essen, brodelnde Stimme (wet voice), Fieber ohne andere Ursache, rezidivierende Pneumonien. Cave: stille Aspiration!",
    rueckseiteB1: "Husten beim Essen, gurgelnde Stimme, Fieber. Achtung: Manchmal merkt man es nicht (stille Aspiration).",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 359; Leitlinie Neurogene Dysphagie DGN 2020",
  },
  {
    id: "le08-kk-22",
    vorderseite: "Wie bereitest du Fingerfood für Walter Bergmann zu?",
    rueckseiteC1: "Mundgerechte, griffige Portionen. Abwechslungsreich, farbig, Lieblingsspeisen einbeziehen. Essen sichtbar und greifbar anrichten.",
    rueckseiteB1: "Kleine Stücke, die man mit den Fingern greifen kann. Was er gerne mag, verschiedene Farben.",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: false,
    quelle: "Leitlinie Demenz DGN/DGPPN 2023; I Care Pflege Thieme 2020, S. 373",
  },
  {
    id: "le08-kk-23",
    vorderseite: "Was tust du bei Verdacht auf Gedeihstörung bei Baby Emre?",
    rueckseiteC1: "Gewicht, Länge, Kopfumfang messen und in Perzentilenkurve eintragen. Trinkverhalten beobachten, Ernährungsprotokoll führen, Kinderarzt informieren.",
    rueckseiteB1: "Baby wiegen und messen, Werte in die Wachstumskurve eintragen. Aufschreiben, wie viel es trinkt. Kinderarzt informieren.",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "Leitlinie Gedeihstörung DGKJ 2020",
  },
  {
    id: "le08-kk-24",
    vorderseite: "Welche Kostform wählst du bei Dysphagie-Stufe 2?",
    rueckseiteC1: "Pürierte, glatte Kost (IDDSI Level 4). Flüssigkeiten andicken (Nektar- bis Honigkonsistenz). Keine Mischkonsistenzen.",
    rueckseiteB1: "Alles püriert und glatt. Getränke dicker machen. Nie flüssig und fest gleichzeitig im Mund.",
    tag: "pflege",
    kategorie: "handlung",
    pruefungsrelevant: true,
    quelle: "IDDSI Framework 2.0; I Care Pflege Thieme 2020, S. 361",
  },

  // ===================================================================
  // ASSESSMENT (7 Karten)
  // ===================================================================

  {
    id: "le08-kk-25",
    vorderseite: "Was erfasst das MNA-Screening?",
    rueckseiteC1: "Mini Nutritional Assessment: 2-stufiges Screening für geriatrische Patienten. Ergebnis: 24–30 normal, 17–23,5 Risiko, < 17 Mangelernährung.",
    rueckseiteB1: "Ein Fragebogen für ältere Menschen: Wie viel isst und wiegt man? Hat man abgenommen?",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: true,
    quelle: "Vellas et al. 2006; I Care Pflege Thieme 2020, S. 343",
  },
  {
    id: "le08-kk-26",
    vorderseite: "Was prüft das NRS-2002-Screening?",
    rueckseiteC1: "Mangelernährungsrisiko im Krankenhaus. Erfasst BMI, Gewichtsverlust, Nahrungszufuhr und Krankheitsschwere. Score ≥ 3 = Intervention nötig.",
    rueckseiteB1: "Ein Test im Krankenhaus: Hat der Patient abgenommen? Isst er genug? Ab 3 Punkten muss man handeln.",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: true,
    quelle: "Kondrup et al. 2003; I Care Pflege Thieme 2020, S. 343",
  },
  {
    id: "le08-kk-27",
    vorderseite: "Wofür steht das MUST-Screening?",
    rueckseiteC1: "Malnutrition Universal Screening Tool: Erfasst BMI, ungeplanten Gewichtsverlust und Nahrungskarenz. 0 = gering, 1 = mittel, ≥ 2 = hohes Risiko.",
    rueckseiteB1: "Ein einfacher Test mit drei Fragen: BMI, Gewichtsverlust und ob man nichts essen konnte.",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: true,
    quelle: "BAPEN MUST Toolkit 2003",
  },
  {
    id: "le08-kk-28",
    vorderseite: "Wie beurteilst du den Hautturgor bei Exsikkose?",
    rueckseiteC1: "Hautfalte am Handrücken oder Sternum bilden. Bleibt sie > 2 Sekunden stehen, liegt eine Dehydratation vor.",
    rueckseiteB1: "Haut am Handrücken zusammendrücken. Bleibt die Falte stehen, hat der Patient zu wenig Wasser.",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 348",
  },
  {
    id: "le08-kk-29",
    vorderseite: "Welche Laborwerte zeigen eine Mangelernährung?",
    rueckseiteC1: "Albumin < 35 g/l, Präalbumin erniedrigt, Transferrin erniedrigt, Lymphozyten < 1500/µl. Albumin reagiert träge (HWZ 20 Tage).",
    rueckseiteB1: "Bestimmte Blutwerte sind zu niedrig, besonders Albumin. Das zeigt, dass der Körper zu wenig Eiweiß bekommt.",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: false,
    quelle: "I Care Pflege Thieme 2020, S. 344",
  },
  {
    id: "le08-kk-30",
    vorderseite: "Wie erkennst du Zeichen einer Dehydratation?",
    rueckseiteC1: "Stehende Hautfalten, trockene Schleimhäute, konzentrierter Urin, Tachykardie, Verwirrtheit, Gewichtsverlust, eingesunkene Augen.",
    rueckseiteB1: "Trockene Lippen, wenig dunkler Urin, Verwirrtheit, schneller Puls, eingesunkene Augen.",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: true,
    quelle: "I Care Pflege Thieme 2020, S. 348",
  },
  {
    id: "le08-kk-31",
    vorderseite: "Wie dokumentierst du ein Essprotokoll korrekt?",
    rueckseiteC1: "Art und Menge der Nahrung, Uhrzeit, geschätzte Portionsgröße, Besonderheiten (Erbrechen, Ablehnung) über mindestens 3 Tage.",
    rueckseiteB1: "Aufschreiben: Was hat der Patient gegessen? Wie viel? Wann? Hat er etwas abgelehnt? Mindestens 3 Tage lang.",
    tag: "pflege",
    kategorie: "assessment",
    pruefungsrelevant: false,
    quelle: "DNQP Expertenstandard Ernährungsmanagement 2017, S. 38",
  },

  // ===================================================================
  // RECHT (7 Karten)
  // ===================================================================

  {
    id: "le08-kk-32",
    vorderseite: "Darf ein Patient die Nahrungsaufnahme verweigern?",
    rueckseiteC1: "Ja. Jeder einwilligungsfähige Patient darf Nahrung und Flüssigkeit ablehnen. Zwangsernährung ist Körperverletzung (§ 223 StGB).",
    rueckseiteB1: "Ja. Wenn ein Patient bei Verstand ist, darf er das Essen ablehnen. Man darf ihn nicht zwingen.",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: true,
    quelle: "§ 223 StGB; § 1901a BGB",
  },
  {
    id: "le08-kk-33",
    vorderseite: "Was regelt § 1901a BGB bei Ernährungsentscheidungen?",
    rueckseiteC1: "Die Patientenverfügung: Ein Patient kann vorab festlegen, ob er künstliche Ernährung wünscht oder ablehnt. Sie ist für Arzt und Betreuer bindend.",
    rueckseiteB1: "In der Patientenverfügung steht, ob jemand eine Sonde möchte oder nicht. Das muss man beachten.",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: true,
    quelle: "§ 1901a BGB",
  },
  {
    id: "le08-kk-34",
    vorderseite: "Wann ist eine PEG bei Walter Bergmann ethisch fragwürdig?",
    rueckseiteC1: "Bei fortgeschrittener Demenz: Studien zeigen keinen Überlebensvorteil durch PEG. Lebensqualität und mutmaßlicher Wille sind abzuwägen.",
    rueckseiteB1: "Bei schwerer Demenz bringt eine PEG oft keinen Vorteil. Man muss überlegen: Was hätte der Patient gewollt?",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: true,
    quelle: "Leitlinie Demenz DGN/DGPPN 2023; Sampson et al. Cochrane Review 2009",
  },
  {
    id: "le08-kk-35",
    vorderseite: "Wer entscheidet über eine PEG bei nicht einwilligungsfähigen Patienten?",
    rueckseiteC1: "Der gesetzliche Betreuer nach § 1901a BGB unter Berücksichtigung der Patientenverfügung bzw. des mutmaßlichen Willens. Im Notfall: Betreuungsgericht.",
    rueckseiteB1: "Der Betreuer entscheidet. Er muss überlegen, was der Patient gewollt hätte. Im Notfall entscheidet das Gericht.",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: true,
    quelle: "§ 1901a, § 1901b BGB",
  },
  {
    id: "le08-kk-36",
    vorderseite: "Welche Rolle spielt Halal-Ernährung in der Pflege?",
    rueckseiteC1: "Kulturelle Ernährungsgewohnheiten sind zu respektieren. Halal: kein Schweinefleisch, kein Alkohol. Pflegekräfte müssen nachfragen und dokumentieren.",
    rueckseiteB1: "Manche Patienten essen nur bestimmtes Essen. Man muss fragen und es aufschreiben.",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: false,
    quelle: "ICN Ethikkodex 2021; Transkulturelle Pflege nach Leininger",
  },
  {
    id: "le08-kk-37",
    vorderseite: "Welche Pflicht hat die Pflegekraft bei Nahrungsverweigerung?",
    rueckseiteC1: "Ursachen erfassen (Schmerzen, Übelkeit, Dysphagie), Maßnahmen einleiten, dokumentieren und Arzt informieren. Keine Zwangsernährung.",
    rueckseiteB1: "Herausfinden warum der Patient nicht essen will. Arzt informieren. Alles aufschreiben. Nie zum Essen zwingen.",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: true,
    quelle: "DNQP Expertenstandard Ernährungsmanagement 2017, S. 50",
  },
  {
    id: "le08-kk-38",
    vorderseite: "Ist es erlaubt, Medikamente heimlich ins Essen zu mischen?",
    rueckseiteC1: "Nein — das ist Körperverletzung nach § 223 StGB, auch bei Demenz. Nur mit Betreuer-Anordnung und richterlicher Genehmigung zulässig.",
    rueckseiteB1: "Nein. Medikamente heimlich ins Essen mischen ist verboten, auch bei Demenz. Das ist strafbar.",
    tag: "pflege",
    kategorie: "recht",
    pruefungsrelevant: true,
    quelle: "§ 223 StGB; I Care Pflege Thieme 2020, S. 175",
  },
];
