// CE-04 Situation „Der wütende Sohn" — Barrel Export
export { CE04_SIT_WAGNER_PATIENT } from "./patient";
export {
  CE04_SIT_WAGNER_WAHRNEHMEN,
  CE04_SIT_WAGNER_EINSCHAETZEN,
  CE04_SIT_WAGNER_INFORMIEREN,
  CE04_SIT_WAGNER_BERATEN,
  CE04_SIT_WAGNER_EVALUIEREN,
  CE04_SIT_WAGNER_DOKUMENTIEREN,
} from "./phases";
